name: Publish simulator archive

on:
  push:
    tags:
      - '**'
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    # checkout@v1 must be used since v2 breaks tags
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Build archive
      id: build_archive
      run: |
        mkdir archive
        NAME="competition-simulator-$(git describe --always --tags).zip"
        ./script/create-archive --output archive/$NAME
        echo "##[set-output name=archive;]$NAME"
    - name: Get tag annotation
      uses: ericcornelissen/git-tag-annotation-action@v1
      id: tag_data
    - name: Create release from tag
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags')
      with:
        body: ${{ steps.tag_data.outputs.git-tag-annotation }}
        token: ${{ secrets.GITHUB_TOKEN }}
        # don't overwrite existing releases
        allowUpdates: false
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: archive/${{ steps.build_archive.outputs.archive }}
        asset_name: ${{ steps.build_archive.outputs.archive }}
        tag: ${{ github.ref }}
        overwrite: true

