name: Create release

on:
  push:
    tags:
      - **

  make-release-from-tag:
    runs-on: ubuntu-latest
    steps:
    # checkout@v1 must be used since v2 breaks tags
    - uses: actions/checkout@v1
    - uses: ericcornelissen/git-tag-annotation-action@v1
      id: tag_data
    - uses: ncipollo/release-action@v1
      with:
        body: ${{ steps.tag_data.outputs.git-tag-annotation }}
        token: ${{ secrets.GITHUB_TOKEN }}
